name: Update README with last commit date

on:
  push:
    branches:
      - main  # or master, depending on your default branch

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get last commit info
        id: git-info
        run: |
          LAST_COMMIT_DATE=$(git log -1 --format="%cd" --date=short)
          TOTAL_COMMITS=$(git rev-list --count HEAD)
          echo "last_commit_date=$LAST_COMMIT_DATE" >> $GITHUB_OUTPUT
          echo "total_commits=$TOTAL_COMMITS" >> $GITHUB_OUTPUT

      - name: Update README.md
        run: |
          sed -i "s/Last Comit:.*/Last Commit: ${{ steps.git-info.outputs.last_commit_date }}/" README.md
          sed -i "s/Total Comits:.*/Total Commits: ${{ steps.git-info.outputs.total_commits }}/" README.md
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m "Auto-update README with latest commit info" || exit 0
          git push
