name: Update README with last commit date

on:
  push:
    branches:
      - main  # or master, depending on your default branch

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get last commit date
        id: last-commit
        run: |
          LAST_COMMIT_DATE=$(git log -1 --format="%cd" --date=short)
          echo "last_commit_date=$LAST_COMMIT_DATE" >> $GITHUB_OUTPUT

      - name: Update README.md
        run: |
          sed -i "s/Last Commit:.*/Last Commit: ${{ steps.last-commit.outputs.last_commit_date }}/" README.md
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m "Update README with latest commit date" || exit 0
          git push
